### ISSUE TITLE
Setup Parse database

### ISSUE THREAD

**Issue by artyymcflyy** [Codepath-Group11/MyMusic#2]

**Comment by kathyLA** [comment]
Basic Parse server setting with mlab , deploy on heroku. 
Below is the reference of  simple setting at index.js for parse server.
Server url at : https://mymusic2017.herokuapp.com/parse

var databaseUri = 'mongodb://dbadmin:contnet#2017@ds033116.mlab.com:33116/codepath_mymusic'

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'com.yerneni.MyMusic',
  masterKey: process.env.MASTER_KEY || 'BABCACF1095628409D2801FD7B2D1C8A2794AD0C727B34CA', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'https://mymusic2017.herokuapp.com/parse',//'http://localhost:1337/parse',  // Don't forget to change to https if needed
  clientKey: '5IgO4kEL53',
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  auth: {
  facebook: {
    appIds: "fb1414535481941160"
  },
  twitter: { consumer_key: "l8wP09DXjmpAilNYKb8WCLe0b", 
             consumer_secret: "fMZ3HD5vzOhKVfdWSqXRnGBYGFXzFkERIHU9XEYkvpGGmpTsLG"
  }

 }
});

**Comment by kathyLA** [comment]
* Client key and Master key are manual generate. need to match with the ios parse sdk when configuration
