### ISSUE TITLE
Connect to One or More Music Services

### ISSUE THREAD

**Issue by artyymcflyy** [Codepath-Group11/MyMusic#4]
A user should be able to connect to multiple (more than 1) subscription/free music services securely.

**Comment by artyymcflyy** [comment]
The app can connect with spotify but getting an api key for other music services is difficult at the moment

**Comment by onlynaresh** [comment]
Trying to find another music service that will serve our purpose. Google,amazon dont have any API's and waiting for sound cloud to approve API key request.
